server:
  port: 8083

spring:
  application:
    name: Post Service

  datasource:
    url: jdbc:postgresql://localhost:5432/PostDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
